version: '3.7'

services:
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: one
    volumes:
      - ./influxdb:/var/lib/influxdb
  grafana:
    image: "grafana/grafana"
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
    volumes:
      - "./grafana/:/var/lib/grafana"
  collector:
    build:
      context: .
    volumes:
      - /var/lib/one/.one/one_auth:/var/lib/one/.one/one_auth:ro
    image: registry.haufe.io/langhammerj/one-influxdb
    environment:
      # ONE_SERVER: 'http://localhost:2633'
      INFLUX_SERVER: influxdb

