{
 "title": "OpenNebula - Overview (Zones + Cluster + Ressources)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "topN", "label": "Top N", "query": "1,2,3,4,5,6,8,10,15,20,40" }
  ]
 },
 "panels": [
  {
   "title": "Used CPU (N)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "query": "SELECT mean(\"usage\") / mean(\"max\") FROM \"host_cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "asPercent(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.used_cpu),sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.max_cpu))"
    }
   ]
  },
  {
   "title": "Used RAM (N)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_memory",
     "query": "SELECT (mean(\"usage\") / mean(\"max\")) * 100  FROM \"host_memory\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "asPercent(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.used_mem),sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.max_mem))"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rvms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "target": "sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.rvms)"
    }
   ]
  },
  {
   "title": "Used RAM (N+1)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "asPercent(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.used_mem),diffSeries(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.max_mem),maxSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.max_mem)))"
    }
   ]
  },
  {
   "title": "Used CPU (N+1)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "asPercent(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.used_cpu),diffSeries(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.max_cpu),maxSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.max_cpu)))"
    }
   ]
  },
  {
   "title": "Top $topN  VMM Hosts  - RAM Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_memory",
     "query": "SELECT top(\"used\",$topN) FROM \"host_memory\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "host, $topN" ], "type": "top" }
      ]
     ],
     "target": "aliasByNode(highestAverage(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.used_mem, $TopRessources), 6)"
    }
   ]
  },
  {
   "title": "Top $topN  VMM Hosts  - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "$topN" ], "type": "top" }
      ]
     ],
     "target": "aliasByNode(highestAverage(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.used_cpu, $TopRessources), 6)"
    }
   ]
  },
  {
   "title": "Top $topN  VMM Hosts  - Running VMs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rvms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "$topN" ], "type": "top" }
      ]
     ],
     "target": "aliasByNode(highestAverage(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.rvms, $TopRessources), 6)"
    }
   ]
  },
  {
   "title": "CPU Allocated vs. Real vs. Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "query": "SELECT mean(\"max\") * 0.01 FROM \"host_cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(sumSeries(scale(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.max_cpu, 0.01)), 'CPU Cores')"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "query": "SELECT mean(\"usage\") * 0.01 FROM \"host_cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(sumSeries(scale(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.cpu_usage, 0.01)), 'CPU Allocated')"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "query": "SELECT mean(\"used\") * 0.01 FROM \"host_cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(sumSeries(scale(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.used_cpu, 0.01)), 'CPU Used')"
    }
   ]
  },
  {
   "title": "RAM Allocated vs. Real vs. Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "RAM GB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_memory",
     "query": "SELECT mean(\"max\") FROM \"host_memory\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.max_mem), 'RAM GB')"
    },
    {
     "alias": "RAM Allocated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_memory",
     "query": "SELECT mean(\"usage\") FROM \"host_memory\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.mem_usage), 'RAM Allocated')"
    },
    {
     "alias": "RAM Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_memory",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.*.used_mem), 'RAM Used')"
    }
   ]
  }
 ]
}