{
 "title": "OpenNebula - VMM Host Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES with key= \"host\";"
   }
  ]
 },
 "panels": [
  {
   "title": "Used CPU",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "query": "SELECT (mean(\"used\") / mean(\"max\")) * 100 FROM \"host_cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "asPercent(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.used_cpu),sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.max_cpu))"
    }
   ]
  },
  {
   "title": "VMM Host CPU Detail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Host Max CPU Shares",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "alias(scale(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.max_cpu, 0.01), 'Host CPU Cores')"
    },
    {
     "alias": "Host Allocated CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "alias(scale(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.cpu_usage, 0.01), 'Host Allocated CPU')"
    },
    {
     "alias": "Host Used CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_cpu",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "alias(scale(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.used_cpu, 0.01), 'Host Used CPU')"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"used\") / mean(\"max\")) * 100 FROM \"host_memory\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "asPercent(sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.used_mem),sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.max_mem))"
    }
   ]
  },
  {
   "title": "VMM Host RAM Detail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "Host RAM GB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_memory",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "alias(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.max_mem, 'Host RAM')"
    },
    {
     "alias": "Host Allocated RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_memory",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "alias(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.mem_usage, 'Host Allocated RAM')"
    },
    {
     "alias": "Host Used RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host_memory",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "alias(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.used_mem, 'Host Used RAM')"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rvms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "sumSeries(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.rvms)"
    }
   ]
  },
  {
   "title": "VMM Host running VMs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rvms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "alias(opennebula-performance.zones.$Zone.clusters.$Cluster.hosts.$Host.rvms, 'Running VMs')"
    }
   ]
  }
 ]
}