{
 "title": "OpenNebula - VDC (Group/vDC Ressources)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Zone", "query": "opennebula-performance.zones.*" },
   { "name": "TopRessources", "query": "1,2,3,4,5,6,8,10,15,20,40" }
  ]
 },
 "panels": [
  {
   "title": "Top $TopRessources vDC RAM Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "quota",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(highestAverage(opennebula-performance.zones.$Zone.vdcs.*.quotas.group_memory_used, $TopRessources), 4)"
    }
   ]
  },
  {
   "title": "Top $TopRessources  vDC CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(opennebula-performance.zones.$Zone.vdcs.*.quotas.group_cpu_used, $TopRessources), 4)"
    }
   ]
  },
  {
   "title": "Top $TopRessources  vDC VMs running",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(opennebula-performance.zones.$Zone.vdcs.*.quotas.group_vms_used, $TopRessources), 4)"
    }
   ]
  },
  {
   "title": "vDC CPU (assigned vs. in use)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(opennebula-performance.zones.$Zone.vdcs.*.quotas.group_cpu), 'vDC assigned CPU')"
    },
    {
     "target": "alias(sumSeries(opennebula-performance.zones.$Zone.vdcs.*.quotas.group_cpu_used), 'vDC in use CPU')"
    }
   ]
  },
  {
   "title": "vDC RAM (Assigned vs. in use)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(opennebula-performance.zones.$Zone.vdcs.*.quotas.group_memory), 'vDC assigned RAM')"
    },
    {
     "target": "alias(sumSeries(opennebula-performance.zones.$Zone.vdcs.*.quotas.group_memory_used), 'vDC in use RAM')"
    }
   ]
  }
 ]
}